GET http://localhost:3000
Authorization: Bearer 7b8134110b2ec7fcbe055eda7b1a62ac3fb8adfd11e1609b02ecc6900bab641c
#####
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "nava",
    "email": "nava@gmail.com",
    "phone_number": 7661060168,
    "password": "12345"
}
####
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "nava@gmail.com",
    "password": "12345"
}
####
POST http://localhost:3000/user/refresh-token
####
DELETE  http://localhost:3000/user/logout