GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTMyMTM0NjMsImV4cCI6MTY5MzIxNzA2MywiYXVkIjoiNjRlYzVlYmNlMDJmMGI3ZGZmN2E4MzI0IiwiaXNzIjoic2F0eWEifQ.e4L5cXxGGP_VR4yjisc6tmKl6CPled69wnVpbNg4QcY
#####
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "satya",
    "email": "satya@gmail.com",
    "phone_number": 7661060169,
    "password": "123456"
}
####
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "satya@gmail.com",
    "password": "123456"
}
####
POST http://localhost:3000/user/refresh-token
####
DELETE  http://localhost:3000/user/logout