GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODkxNzU3NjUsImV4cCI6MTY4OTE3NTc5NSwiYXVkIjoiNjRhZDQwMzZkYjUwMGQ1Y2VmNjRmZGM1IiwiaXNzIjoic2F0eWEifQ.IWsrOPnRqPf9xAwDiWjh1UCutWyZ9ywHRVwWBXZ7BlY
#####
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "nava",
    "email": "nava@gmail.com",
    "phone_number": 7661060168,
    "password": "12345"
}
####
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "nava@gmail.com",
    "password": "12345"
}
####
POST http://localhost:3000/user/refresh-token
####
DELETE  http://localhost:3000/user/logout